#pragma once
#include "core/binder_common.hpp"
#include <fmod_studio_common.h>
VARIANT_ENUM_CAST(FMOD_STUDIO_LOADING_STATE);
VARIANT_ENUM_CAST(FMOD_STUDIO_LOAD_MEMORY_MODE);
VARIANT_ENUM_CAST(FMOD_STUDIO_PARAMETER_TYPE);
VARIANT_ENUM_CAST(FMOD_STUDIO_USER_PROPERTY_TYPE);
VARIANT_ENUM_CAST(FMOD_STUDIO_EVENT_PROPERTY);
VARIANT_ENUM_CAST(FMOD_STUDIO_PLAYBACK_STATE);
VARIANT_ENUM_CAST(FMOD_STUDIO_STOP_MODE);
VARIANT_ENUM_CAST(FMOD_STUDIO_INSTANCETYPE);
VARIANT_ENUM_CAST(FMOD_RESULT)

