#pragma once
#include "classes/object.hpp"
#include "core/binder_common.hpp"
#include "core/class_db.hpp"
#include <fmod_studio_common.h>

class Fmod : godot::Object
{
  protected:
    static void _bind_methods()
    {
        // FMOD_STUDIO_LOADING_STATE
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOADING_STATE_LOADING)
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOADING_STATE_LOADED)
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOADING_STATE_UNLOADED)
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOADING_STATE_UNLOADING)
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOADING_STATE_ERROR)

        // FMOD_STUDIO_LOAD_MEMORY_MODE
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOAD_MEMORY)
        BIND_ENUM_CONSTANT(FMOD_STUDIO_LOAD_MEMORY_POINT)

        // FMOD_STUDIO_PARAMETER_TYPE | Unused so don't expose
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_GAME_CONTROLLED);
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE);
        //
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE);
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION);
        //
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION);
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION);
        //
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION);
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED);
        //
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE);
        // BIND_ENUM_CONSTANT(FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED);

        // FMOD_STUDIO_EVENT_PROPERTY
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN);

        // FMOD_STUDIO_PLAYBACK_STATE
        BIND_ENUM_CONSTANT(FMOD_STUDIO_PLAYBACK_PLAYING);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_PLAYBACK_SUSTAINING);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_PLAYBACK_STOPPED);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_PLAYBACK_STARTING);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_PLAYBACK_STOPPING);

        // FMOD_STUDIO_STOP_MODE
        BIND_ENUM_CONSTANT(FMOD_STUDIO_STOP_ALLOWFADEOUT);
        BIND_ENUM_CONSTANT(FMOD_STUDIO_STOP_IMMEDIATE);
    }
};
VARIANT_ENUM_CAST(FMOD_STUDIO_LOADING_STATE);
VARIANT_ENUM_CAST(FMOD_STUDIO_LOAD_MEMORY_MODE);
VARIANT_ENUM_CAST(FMOD_STUDIO_EVENT_PROPERTY);
VARIANT_ENUM_CAST(FMOD_STUDIO_PLAYBACK_STATE);
VARIANT_ENUM_CAST(FMOD_STUDIO_STOP_MODE);
VARIANT_ENUM_CAST(FMOD_RESULT);
// Unused
// VARIANT_ENUM_CAST(FMOD_STUDIO_PARAMETER_TYPE);
// VARIANT_ENUM_CAST(FMOD_STUDIO_USER_PROPERTY_TYPE);
// VARIANT_ENUM_CAST(FMOD_STUDIO_INSTANCETYPE);
